tailwind.config = {
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-on-surface": "#fdeee7",
        "on-primary-fixed-variant": "#89153d",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "surface-container-low": "#fff1ea",
        "surface-bright": "#fff8f5",
        "primary-container": "#fb6f92",
        "on-tertiary-fixed-variant": "#57423e",
        "tertiary-container": "#b39893",
        "secondary": "#80515e",
        "outline": "#8a7175",
        "on-secondary-fixed": "#32101b",
        "primary-fixed": "#ffd9df",
        "tertiary": "#705955",
        "surface-variant": "#eee0d9",
        "error-container": "#ffdad6",
        "surface-tint": "#a93054",
        "secondary-fixed": "#ffd9e1",
        "on-tertiary": "#ffffff",
        "surface": "#fff8f5",
        "tertiary-fixed": "#fbdcd7",
        "secondary-container": "#fec1d0",
        "on-tertiary-fixed": "#281715",
        "surface-dim": "#e5d7d0",
        "on-secondary": "#ffffff",
        "background": "#fff8f5",
        "surface-container-lowest": "#ffffff",
        "primary": "#a93054",
        "on-background": "#211a16",
        "outline-variant": "#ddbfc3",
        "inverse-primary": "#ffb1c0",
        "status-available": "#FB6F92",
        "on-tertiary-container": "#44312d",
        "inverse-surface": "#372f2a",
        "surface-container-high": "#f4e5de",
        "on-primary-fixed": "#3f0016",
        "error": "#ba1a1a",
        "surface-container-highest": "#eee0d9",
        "secondary-fixed-dim": "#f2b7c5",
        "status-reserved": "#E9C46A",
        "status-bought": "#382623",
        "on-surface": "#211a16",
        "surface-container": "#faebe4",
        "on-surface-variant": "#574145",
        "on-error": "#ffffff",
        "tertiary-fixed-dim": "#ddc0bb",
        "on-primary-container": "#6f002c",
        "on-secondary-container": "#7b4c59",
        "primary-fixed-dim": "#ffb1c0",
        "on-secondary-fixed-variant": "#653a46"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        "stack-md": "16px",
        "stack-lg": "32px",
        "stack-sm": "8px",
        "margin-mobile": "24px",
        "margin-desktop": "64px",
        "gutter": "20px",
        "container-max": "1200px"
      },
      fontFamily: {
        "headline-h5": ["Montserrat", "sans-serif"],
        "headline-h3": ["Montserrat", "sans-serif"],
        "body-md": ["Montserrat", "sans-serif"],
        "headline-h2": ["Montserrat", "sans-serif"],
        "display-hero-mobile": ["Playfair Display", "serif"],
        "display-hero": ["Playfair Display", "serif"],
        "label-caps": ["Montserrat", "sans-serif"],
        "body-lg": ["Montserrat", "sans-serif"],
        "headline-h4": ["Montserrat", "sans-serif"],
        "headline-h2-mobile": ["Montserrat", "sans-serif"]
      },
      fontSize: {
        "headline-h5": ["25px", { lineHeight: "1.3", fontWeight: "300" }],
        "headline-h3": ["38px", { lineHeight: "1.2", fontWeight: "300" }],
        "body-md": ["16px", { lineHeight: "1.5", fontWeight: "300" }],
        "headline-h2": ["48px", { lineHeight: "1.2", fontWeight: "300" }],
        "display-hero-mobile": ["42px", { lineHeight: "1.1", fontWeight: "400" }],
        "display-hero": ["60px", { lineHeight: "1.1", fontWeight: "400" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.1em", fontWeight: "300" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "300" }],
        "headline-h4": ["30px", { lineHeight: "1.3", fontWeight: "300" }],
        "headline-h2-mobile": ["32px", { lineHeight: "1.2", fontWeight: "300" }]
      }
    }
  }
};
